Update j2 template

diff --git a/j2 template b/j2 template
--- a/j2 template
+++ b/j2 template
@@ -1,4 +1,3 @@
-
 #!/bin/bash
 
 # Log cleanup job for {{ job_name }}
@@ -6,12 +5,18 @@
 # Time to run: {{ time_to_run }}
 # Host: {{ ansible_host }}
 
-# Path to the log manager script
+# Paths to the log manager scripts
 log_manager_script="{{ path_job }}/linux-log-manager.sh"
+log_rotation_script="{{ path_job }}/log-rotation.sh"
 
-# Ensure the log manager script exists
+# Ensure the log manager scripts exist
 if [ ! -f "$log_manager_script" ]; then
     echo "Error: Log manager script not found at $log_manager_script"
+    exit 1
+fi
+
+if [ ! -f "$log_rotation_script" ]; then
+    echo "Error: Log rotation script not found at $log_rotation_script"
     exit 1
 fi
 
@@ -33,8 +38,9 @@ fi
 # Backup Path: {{ service.path }}/backup
 {% endif %}
 {% endif %}
-# Type: {{ service.type }}
+# Clean Type: {{ service.clean_type }}
 
+{% if service.clean_type == 'retention' %}
 # Call the linux-log-manager script for {{ service.name }}
 $log_manager_script \
     --service "{{ service.name }}" \
@@ -46,11 +52,4 @@ $log_manager_script \
     {% if service.backup_path is defined %} --backup-path "{{ service.backup_path }}" {% endif %}
 
 if [ $? -ne 0 ]; then
-    echo "Error: Log cleanup failed for {{ service.name }}"
-else
-    echo "Log cleanup succeeded for {{ service.name }}"
-fi
-
-{% endfor %}
-
-echo "Log cleanup and backup completed for {{ job_name }} on {{ ansible_host }}"
+    echo
